### DO NOT EDIT THIS FILE ###
export OB_PROJECT_ID     := lora4linux
export OB_TYPE           := yocto
export OB_DEFCONFIG_DIR  := ${CURDIR}/configs
export OB_INITENV_SCRIPT := ${CURDIR}/platform/poky/oe-init-build-env

include platform/openbar/core/main.mk
### DO NOT EDIT THIS FILE ###
